name: CI

on: [push, pull_request]

jobs:
  phpcs:
    name: Code style
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          ini-values: memory_limit=-1, date.timezone='UTC'
          tools: phpcs

      - name: Check production code style
        run: phpcs src/

      - name: Check test code style
        run: phpcs tests/ --standard=tests/phpcs.xml
  tests:
    runs-on: ubuntu-latest

    env:
      COMPOSER_ROOT_VERSION: 3.99.99

    strategy:
      matrix:
        php: [8.0, 8.1, 8.2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction --no-suggest

    - name: Run test suite
      run: php vendor/bin/codecept run
